const nodemailer = require('nodemailer')
require('dotenv').config()

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
})

const sendFakeNewsAlert = async (topic, headline, source) => {
  const mailOptions = {
    from: process.env.EMAIL_USER,
    to: process.env.ALERT_EMAIL,
    subject: `🚨 TruthCheck Alert: Fake News Detected - ${topic}`,
    html: `
      <div style="font-family: Arial; max-width: 600px; margin: auto;">
        <h2 style="color: #ef4444;">🚨 Fake News Alert</h2>
        <p><strong>Topic:</strong> ${topic}</p>
        <p><strong>Headline:</strong> ${headline}</p>
        <p><strong>Source:</strong> ${source}</p>
        <p style="color: #94a3b8; font-size: 0.9rem;">
          This alert was generated by TruthCheck AI system.
        </p>
        <a href="http://localhost:5173" 
           style="background: #38bdf8; color: #0f172a; padding: 0.5rem 1rem; 
                  border-radius: 8px; text-decoration: none;">
          View on TruthCheck
        </a>
      </div>
    `
  }

  try {
    await transporter.sendMail(mailOptions)
    console.log('Alert email sent! ✅')
  } catch (error) {
    console.log('Email error:', error.message)
  }
}

// Test
sendFakeNewsAlert(
  'Political Misinformation',
  'SHOCKING: Government secretly planning new tax on WhatsApp!',
  'postcard.news'
)